### ISSUE TITLE
V1.0.0 issue

### ISSUE THREAD

**Issue by ghost** [teifip/gcic-mqtt-client#2]
I had a code working with the V 0.1.0 but now with the V 1.0.0 just throw me an error: Username is required to use a password. 
![image](https://user-images.githubusercontent.com/33207696/39162461-37e7a07e-473b-11e8-86e8-2d9d85677e1f.png)

**Comment by teifip** [comment]
@juddelgadoch Thanks for reporting the issue! The `gcic-mqtt-client` helper currently does not set any value as `username` since the value is anyhow irrelevant for [Google Cloud IoT Core](https://cloud.google.com/iot-core/).  Apparently something has changed either in the [MQTT.js](https://www.npmjs.com/package/mqtt) library or in [Google Cloud IoT Core](https://cloud.google.com/iot-core/), and the connection gets rejected if attempted without a `username`. This should be easy to fix. Just give me time to set-up the test environment...

**Comment by teifip** [comment]
Just published revision 1.0.1 to [npm](https://www.npmjs.com/package/gcic-mqtt-client). Again, thanks @juddelgadoch for reporting the issue.
